name: build publish

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build nar
        run: |
          ./build.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/out/*.nar"
          prerelease: true
