name: full pack build

on:
  schedule: # 每月的第2天的0点0分
    - cron: "0 0 2 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: remove unneeded files
        run: |
          rm -rf "Taromati2/shell/Entire bare"
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Taromati2_full
          path: Taromati2
